### ISSUE TITLE
Installere fuzzy matching

### ISSUE THREAD

**Issue by raae** [lesersokerbok/lsb-wpengine#49]
https://searchwp.com/docs/extensions/fuzzy-matches/

**Comment by testower** [comment]
Fuzzy matching bruker mysql sin interne soundex funksjon, som bare fungerer for engelsk språk, ikke norsk.

**Comment by raae** [comment]
Tenkte meg det.

**Comment by testower** [comment]
En *mulig* løsning kan være å injecte double metaphone funksjonen inn i mysql, og skrive en fuzzy match utvidelse som bruker denne i stedet for SOUNDEX. Men vet ikke hvor glade wpengine er i den type akrobatikk...

**Comment by raae** [comment]
Tror ikke vi satser på det nå, men hadde vært kult å få til noe rundt
dette. Så kan vi dele de to "norske" utvidelsene av search wp :D

2015-01-14 10:04 GMT+01:00 Tom Erik Støwer <notifications@github.com>:

> En *mulig* løsning kan være å injecte double metaphone funksjonen inn i
> mysql, og skrive en fuzzy match utvidelse som bruker denne i stedet for
> SOUNDEX. Men vet ikke hvor glade wpengine er i den type akrobatikk...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lesersokerbok/lsb-wordpress-themes/issues/49#issuecomment-69887342>
> .
>



-- 
Benedicte | bGraphic <http://bgraphic.no> | 97667045

**Comment by raae** [comment]
Invalid med Algolia.
